apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-yyaz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-imsz-tenant/appstudio/dc-metro-map-yyaz@sha256:e1886b9cc22c858ba50182d249a6a7774d1e302c8f5a0a34b06b8480f5277003
        name: my-nodejs
        resources: {}
status: {}
